name: Issue-Watchers
 
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Run Action
        uses: TesseractCoding/Issue_Watcher@main
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          author: '${{github.actor}}'
          repo: anushkrishnav/Tester
          maxIssue: 2
